
Preliminaries.

```{r}
rm(list=ls())
library(dplyr)
library(tidyr)
```

Read in files and consolidate to the same directory. 

```{r}
d.raw <- data.frame()

files <- dir("perceptual_et/")
ntrials <- 38

condition <- c(1:8)
final_stim <- c("chair_grapes_a.BMP","icecream_bicycle_a.BMP","shoe_pizza_a.BMP", "jacket_pillow_a.BMP", "chair_grapes_a.BMP","icecream_bicycle_a.BMP","shoe_pizza_a.BMP", "jacket_pillow_a.BMP")
condition_stim <- as.data.frame(cbind(condition, final_stim))

demo <- read.csv("demographics.csv") %>%
  select(ID, condition)

demo$condition <- as.factor(demo$condition)

demo <- demo %>%
  left_join(condition_stim)

condition_1_4 <- c("Left","Left","Right","Left","Right","Left","Right","Right","Left","Right", "Right","Left","Left","Right","Left","Left","Right","Right","Right","Left")
  
condition_5_8 <- c("Right","Right","Left","Right","Left","Right","Left","Left","Right","Left","Left","Right","Right","Left","Right","Right","Left","Left","Left","Right")

for (f in files) {
    
  #Get data
  jf <- paste("perceptual_et/",f,sep="")
  jd <- read.table(jf, header = TRUE)
  data <- jd[,1:3]
  
  id <- str_replace(f,"-Event-Data.tsv","")
  id <- as.numeric(id)
  
  #Get the name of the final stimulus in the file based on condition
  final_bmp <- as.character(demo$final_stim[demo$ID == id])
  
  #Get total number of rows.
  num_rows <- nrow(data)
  
  #Set y as final row of file.
  y <- as.character(data[num_rows,3])
  
  #Start at final row and count backwards to final stimulus presented.
  while (y != final_bmp) {
    y <- data[num_rows,3]; 
    num_rows <- num_rows-1}
  
  goodrows <- num_rows
  
  #Cut off data file after final response.
  data <- data[1:goodrows,]
  
  #Creates subset of data with Descriptors referring to accuracy (Left, Right or Space if skipped)
  data_trials <- subset(data, Descriptor == "Space" | Descriptor == "Left" | Descriptor == "Right")
  
  num_rows <- nrow(data_trials)
 
  #Creates an array of length 40 that alternates between subject response ("resp") and space for next      trial ("nexttrial")
  TrialType <- rep(c("resp","nexttrial"),20)
  TrialType <- TrialType[-c(40)]
  
  #Determines number of additional rows in beginning referring to practice trials
  additional_rows <- num_rows - 38
  
  #Removes rows in the beginning
  data_trials <- data_trials[additional_rows:num_rows,]
  
  #add column Trial Type that distinguishes between response and next trial
  data_trials <- cbind(data_trials, TrialType)
  
  #subset only those trials that are subject response trials
  data_trials <- subset(data_trials, TrialType=="resp")
  
  #Change Descriptor to a character variable and then create a matrix with the Descriptor (subject responses) and accurate responses (condition)
  data_trials$Descriptor <- as.character(data_trials$Descriptor)
  
  trial = c(1:20)
  
  cond <- as.character(demo$condition[demo$ID == id])
  
  if(cond %in% 1:4){correct_response <- condition_1_4}
  if(cond %in% 5:8){correct_response <- condition_5_8}
  
  responses <- data.frame(ID = id,
                   trial = trial,
                   response = data_trials$Descriptor,
                   correct_response = correct_response)
  
  d.raw <- bind_rows(d.raw, responses)
}

d.raw <- d.raw %>%
  mutate(acc = NA)

d.raw$acc[d.raw$response== d.raw$correct_response] <- 1
d.raw$acc[d.raw$response!= d.raw$correct_response] <- 0
d.raw$acc[d.raw$response== "Space"] <- NA
d.raw$acc <- as.factor(d.raw$acc)

read_out_folder <-'perceptual_et_processed/'
write.table(d.raw,paste(read_out_folder,'AllSubs_ET.csv',sep=""), sep=",", row.names=FALSE)
```
