---
title: "Toddler Uncertainty Monitoring"
author: "Emily"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: true
---

<style type="text/css">
body, td {
   font-size: 14px;
}
code {
  font-size: 11px;
}
pre {
  font-size: 11px;
}
</style>

Data analysis of toddler uncertainty monitoring study.

# Data preprocessing

Preliminaries.

```{r echo=FALSE}
setwd("~/Desktop/tadpole_t1_data/analysis")
rm(list=ls())
knitr::opts_chunk$set(fig.width=8, fig.height=5, 
                      echo=TRUE, warning=FALSE, message=FALSE, cache=TRUE)
suppressPackageStartupMessages(c("dplyr","langcog","tidyr","ggplot2","lme4"))
library(langcog)
library(plyr)
library(dplyr)
library(RWiener)
library(ggplot2)
library(rjson)
library(stringr)
library(tidyr)
library(lme4)
library(xtable)
library(knitr)
library(markdown)
theme_set(theme_bw())
```

Read in data file.

```{r}
d.raw <- read.csv("AllSubs_ET.csv", header = TRUE) 
d.raw$ID <- d.raw$Subject_ID
d.raw_trans <- read.csv("Fixations_Perceptual.csv", header = TRUE)
d.raw_trans$ID <- str_replace_all(d.raw_trans$ID, "_", "")
d.raw_trans$ID <- as.numeric(d.raw_trans$ID)
d.raw <-d.raw %>%
  left_join(d.raw_trans)
```

Make data tidy.

```{r}
d_acc<- d.raw %>%
  select(Subject_ID, acc1, acc2, acc3, acc4, acc5, acc6, acc7, acc8, acc9, acc10, acc11, acc12, acc13, acc14, acc15, acc16, acc17, acc18, acc19, acc20)%>%
  gather(trial, acc, acc1:acc20) 

d_trans <- d.raw %>%
  select(ID, fixations_1, fixations_2, fixations_3, fixations_4, fixations_5, fixations_6, fixations_7, fixations_8, fixations_9, fixations_10, fixations_11, fixations_12, fixations_13, fixations_14, fixations_15, fixations_16, fixations_17, fixations_18, fixations_19, fixations_20) %>%
  gather(trial, trans, fixations_1:fixations_20) 

d_acc$trial <-str_replace(d_acc$trial, "acc","")
d_trans$trial <- str_replace(d_trans$trial, "fixations_","")

d <- d_acc %>%
  left_join(d_trans) %>%
  select(ID, trial, acc, trans)

d$acc[d$acc==999] <- NA
```

Read in trial info and demographics. 

```{r}
# demo <- read.csv("demographics.csv") 
trial_info <- read.csv("conditions.csv", header = TRUE)
trial_info$trial <- as.character(trial_info$trial)
```

Join trial info and demographics with raw data.

```{r}
d <- left_join(d, trial_info)

d <- d %>% 
  mutate(similarity_condition = ifelse(similarity == 1, "high-similarity",
                                       "low-similarity"))
```

Descriptives.

```{r}

ms <- d %>%
  filter(!is.na(similarity_condition))%>%
  group_by(similarity_condition)%>%
  multi_boot_standard(col = "acc", na.rm = TRUE)

ggplot(ms, aes(x = factor(similarity_condition), y = mean)) + geom_bar(stat = "identity") + 
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper), 
             position = position_dodge(width = .9)) +
  xlab("Similarity") + 
  ylab("Proportion Accurate")

d$acc <- as.factor(d$acc)
ms <- d %>%
  group_by(acc, similarity_condition)%>%
  multi_boot_standard(col = "trans", na.rm = TRUE)

ggplot(ms, aes(x = factor(acc), y = mean)) + geom_bar(stat = "identity") + 
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper), 
             position = position_dodge(width = .9)) +
  xlab("Accuracy") + 
  ylab("Number of switches") + 
  facet_wrap(~similarity_condition)
```

```{r}
glm_maximal_mod <- lmer(trans ~ acc * similarity +
                           (acc * similarity | ID), 
                         data = filter(d))

coefs <- data.frame(coef(summary(glm_maximal_mod)))
# use normal distribution to approximate p-value
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs
```

